backend:
  name: git-gateway
  accept_roles: #optional - accepts all users if left out
    - admin
    - editor
  branch: develop

media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"

collections:
  - name: posts
    label: Posts
    slug: "{{slug}}"
    folder: "content/blog/posts"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "date" }
      - { label: "Categories", name: "categories", widget: "relation", collection: "categories", multiple: true, searchFields: ["title"], valueField: "title", displayFields: ["title"] }
      - { label: "Tags", name: "tags", widget: "relation", collection: "tags", multiple: true, searchFields: ["title"], valueField: "title", displayFields: ["title"] }
      - { label: "Keywords", name: "keywords", widget: "list" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: categories
    label: Categories
    folder: "content/blog/categories"
    create: true
    fields:
      - label: "Name"
        name: "title"
        wisget: "string"

  - name: tags
    label: Tags
    folder: "content/blog/tags"
    create: true
    fields:
      - label: "Name"
        name: "title"
        wisget: "string"

  - label: "Pages"
    name: "pages"
    files:
      - label: "Privacy policy"
        name: "privacy-policy"
        file: "content/site/privacy.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}