backend:
  name: bitbucket
  repo: simokhalil/kelyo.fr # Path to your Bitbucket repository
  branch: master
  auth_type: implicit
  app_id: cbd9ZAaYr7nmFp7An7 # The Key from your Bitbucket settings

media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: blog
    label: Blog
    folder: blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
      - {label: "Image", name: "image", widget: "image"}